### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by smaragdus** [shpati/Journalista#1]
@shpati 

First of all, I would like to say that I like this program- tiny, light, portable, clean interface, good work, thanks.

There are two features that I would like to see implemented:

- system tray support- an option to minimize the program to system tray, in stead of sitting all the time in the task bar for me it would be better if the program could be minimized to system tray (new check box in settings- Minimize Program to System Tray) and restored only when needed;
- URL/mailto links detection- if Journalista could detect URLs and mail links the user would be able to open these links in default browser and default mail client. For me links detection would be extremely convenient to open links automatically in stead of using copy/paste;

I hope that the project is not abandoned and that these two features won't be very hard to be implemented.

Regards

**Comment by shpati** [comment]
Hi @smaragdus. 

The system tray support functionality that you suggested is now implemented. Check it out in the 2.0.1 release. 
Regarding the link detection proposal, I thought about it but want to keep the program light and distraction-free (i.e. text only), so I decided not to implement this proposed feature.

Regards

**Comment by smaragdus** [comment]
@shpati 

First, thank you very much for adding system tray support!

I tested the latest version ([2.0.1](https://github.com/shpati/Journalista/releases/tag/2.0.1)) and it works fine:

![Journalista 2 0 1 0 - 2022-08-22 - 001](https://user-images.githubusercontent.com/9025757/185815779-5c6de0d1-b28a-457b-a410-b71349190bf0.png)

Until now I had to use an external tool ([SmartSystemMenu](https://github.com/AlexanderPro/SmartSystemMenu)) to minimize the program to system tray:

![Journalista 2 0 1 0 - 2022-08-22 - 004](https://user-images.githubusercontent.com/9025757/185815933-9f06ef21-d2d0-45c0-b2be-683186c052a6.png)

But now that [Journalista](https://github.com/shpati/Journalista) supports minimization to system tray I no longer need to right-click on the title bar to minimize it to tray.

About link detection, I understand and accept your decision. What I meant was something like that:

![AkelPad 4 6 0 - 2022-08-22 - 001](https://user-images.githubusercontent.com/9025757/185816333-1e322d2b-a9b8-4039-8142-5d571b92668f.png)

By the way the simple text editor I use- [AkelPad](https://sourceforge.net/projects/akelpad/), is also small and light (406 KB for x32 version and 528 KB for x64 version).

Regards

**Comment by shpati** [comment]
@smaragdus understood, but as I said I want to keep it distraction-free. I did add a new feature in version 2.0.2, which allows the program to remind the user at a pre-defined hour to use the program. This can be useful in establishing the habit of journaling.
